name = "nummet"
version = "0.1.0"
license = "license"
author = "aenlemmea"
maintainer = "aenlemmea"
copyright = "Copyright 2025, aenlemmea"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib = "*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"

[preprocess]
[preprocess.cpp]